[package]
name = "langshift"
version = "0.1.0"
edition = "2024"

[dependencies]
diffsol = { version = "0.6.4", features = ["diffsl", "diffsl-cranelift"] }
plotly = { version = "0.13.3", features = ["static_export_default"] }
yew = { version = "0.21.0", features = ["csr"] }
